-- 코드를 입력하세요
WITH BORROW_TYPE AS
(
    SELECT DISTINCT C.CAR_ID, CAR_TYPE, DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR AS C
    WHERE C.CAR_TYPE IN ('세단', 'SUV')
    AND C.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RH
        WHERE RH.START_DATE <= "2022-11-30"
        AND RH.END_DATE >= "2022-11-01"
    )
    GROUP BY CAR_ID
)

# SELECT *
# FROM BORROW_TYPE

SELECT CAR_ID, BT.CAR_TYPE, ROUND(30 * (DAILY_FEE * (100 - DISCOUNT_RATE) DIV 100)) AS FEE
FROM BORROW_TYPE AS BT
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DP ON BT.CAR_TYPE = DP.CAR_TYPE
WHERE duration_type = "30일 이상" 
AND (30 * (DAILY_FEE * (100 - DISCOUNT_RATE) / 100)) >= 500000 
AND (30 * (DAILY_FEE * (100 - DISCOUNT_RATE) / 100)) < 2000000
ORDER BY 3 DESC, 2, 1 DESC

# SELECT *
# FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
# WHERE START_DATE NOT BETWEEN "2022-11-01" AND "2022-11-30"
# AND END_DATE NOT BETWEEN "2022-11-01" AND "2022-11-30"