# -- 코드를 입력하세요

SELECT date_format(SALES_DATE, '%Y-%m-%d') AS SALES_DATE, 
PRODUCT_ID,	USER_ID, SALES_AMOUNT
FROM 
(
    SELECT SALES_DATE,	PRODUCT_ID,	USER_ID, SALES_AMOUNT
    FROM ONLINE_SALE
    UNION
    SELECT SALES_DATE,	PRODUCT_ID,	NULL, SALES_AMOUNT
    FROM OFFLINE_SALE
) AS A

WHERE year(SALES_DATE) = '2022' AND month(SALES_DATE) = '03'
order by SALES_DATE, PRODUCT_ID, USER_ID
