-- 코드를 입력하세요
-- 보호소에 들어올 때 중성화 되지 않은 동물
WITH INS AS (
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_INS
    WHERE SUBSTRING_INDEX(SEX_UPON_INTAKE, " ", 1) = "Intact"
), OUTS AS
(
    -- 보호소에 나올 때 중성화된 동물
    SELECT ANIMAL_ID, ANIMAL_TYPE, NAME
    FROM ANIMAL_OUTS
    WHERE SUBSTRING_INDEX(SEX_UPON_OUTCOME, " ", 1) != "Intact"
)


SELECT INS.ANIMAL_ID, INS.ANIMAL_TYPE, INS.NAME
FROM INS
JOIN OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
ORDER BY 1