-- 코드를 입력하세요
WITH RECURSIVE T AS (
    SELECT 0 AS HOURS
    UNION ALL
    SELECT HOURS + 1
    FROM T
    WHERE HOURS < 23
)

SELECT HOURS, COUNT(ANIMAL_ID)
FROM T
LEFT JOIN ANIMAL_OUTS on T.HOURS = HOUR(ANIMAL_OUTS.DATETIME)
GROUP BY HOURS