-- 코드를 입력하세요
WITH JY AS 
(
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS orders
    FROM JULY
    GROUP BY FLAVOR
),
WH AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS orders
    FROM FIRST_HALF
    GROUP BY FLAVOR
)


SELECT JY.FLAVOR
FROM JY, WH
WHERE JY.FLAVOR = WH.FLAVOR
ORDER BY (JY.orders + WH.orders) DESC
LIMIT 3