-- 코드를 입력하세요
SELECT CATEGORY, max(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE PRICE in
(
    SELECT max(PRICE)
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)
GROUP BY CATEGORY
HAVING CATEGORY in ('과자', '국', '김치', '식용유')
ORDER BY max(PRICE) DESC