-- 코드를 입력하세요
WITH BOOKS AS (
    SELECT BOOK.CATEGORY, SUM(BOOK_SALES.SALES) AS TOTAL_SALES-- SUM(*) AS TOTAL_SALES
    FROM BOOK, BOOK_SALES
    WHERE BOOK.BOOK_ID = BOOK_SALES.BOOK_ID AND
    year(BOOK_SALES.SALES_DATE) = '2022' AND month(BOOK_SALES.SALES_DATE) = '01'
    GROUP BY CATEGORY
    ORDER BY 1
)

SELECT *
FROM BOOKS