G = input()
if G == "A+": print(4.3)
elif G == "A0": print(4.0)
elif G == "A-": print(3.7)
elif G == "B+": print(3.3)
elif G == "B0": print(3.0)
elif G == "B-": print(2.7)
elif G == "C+": print(2.3)
elif G == "C0": print(2.0)
elif G == "C-": print(1.7)
elif G == "D+": print(1.3)
elif G == "D0": print(1.0)
elif G == "D-": print(0.7)
elif G == "F": print(0.0)
