-- 코드를 입력하세요
SELECT REST_INFO.REST_ID, REST_NAME, FOOD_TYPE, FAVORITES, ADDRESS, ROUND(AVG(REVIEW_SCORE), 2)
FROM REST_INFO, REST_REVIEW
WHERE REST_INFO.REST_ID = REST_REVIEW.REST_ID
    AND SUBSTRING_INDEX(REST_INFO.ADDRESS, " ", 1)  LIKE "서울%"
GROUP BY REST_INFO.REST_ID
ORDER BY ROUND(AVG(REVIEW_SCORE), 2) DESC, FAVORITES DESC