-- 코드를 입력하세요
SELECT MEMBER_ID, MEMBER_NAME, GENDER, date_format(DATE_OF_BIRTH, '%Y-%m-%d')
FROM MEMBER_PROFILE
WHERE TLNO is not NULL and month(DATE_OF_BIRTH) = 3 and GENDER = "W"
Order by MEMBER_ID ASC